services:
  nextjs:
    image: node:22-alpine
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '8888:8888'
    environment:
      - NODE_ENV=production 
      - MONGODB_URI=mongodb://root:example@mongo:27017/ways?authSource=admin
    command: sh -c "npm install --include=dev && npm run build && npm start"
    depends_on:
      - mongo
    restart: always
    mem_limit: 2g
    memswap_limit: 4g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 120s
      timeout: 12s
      retries: 3

  mongo:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always

volumes:
  mongodb_data:
